// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qztizhliagwxkhpgbsje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dGl6aGxpYWd3eGtocGdic2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDI1MzEsImV4cCI6MjA2NDcxODUzMX0.1s0N6E4p1nNkgiU42DayugefyeeRvZWj6dfcQFnDj1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);